project_name: sealed-secrets
env:
  - CGO_ENABLED=0
builds:
  - binary: controller
    id: controller
    main: ./cmd/controller
    ldflags:
      - -X main.VERSION={{ .Version }}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
