name: Release Carvel package

on:
  push:
    paths:
      # update this file to trigger Carvel package release
      - 'carvel/package.yaml'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.4
        with:
          version: v3.4.2

      - name: Install Carvel
        uses: carvel-dev/setup-action@v1.3.0
        with:
          only: kbld, imgpkg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq
        run: |
          mkdir -p ~/bin
          wget https://github.com/mikefarah/yq/releases/v4.30.8/download/yq_linux_amd64 -O ~/bin/yq
          chmod +x ~/bin/yq

      - name: Get Carvel bundle version
        run: |
          export PATH=~/bin:$PATH
          echo "carvel_version=$(yq .spec.version < ./carvel/package.yaml)" >> $GITHUB_ENV


      - name: Create imglock file
        working-directory: ./helm
        run: |
          mkdir -p .imgpkg
          kbld -f <(helm template sealed-secrets) --imgpkg-lock-output .imgpkg/images.yml
          ls -la
          ls -la .imgpkg
          cat .imgpkg/images.yml
          git status
          echo "${{ env.carvel_version }}"

      - name: Push imgpkg bundle
        working-directory: ./helm
        env:
          IMGPKG_ACTIVE_KEYCHAINS: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          imgpkg push -b ghcr.io/alemorcuq/sealed-secrets-carvel:${{ env.carvel_version }} -f .

