name: Publish Release

on:
  workflow_dispatch:
    inputs:
      chart:
        description: 'Chart version (e.g. 2.11.3)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      controller_dockerhub_image_name: docker.io/bitnami/sealed-secrets-controller
      controller_ghcr_image_name: ghcr.io/bitnami-labs/sealed-secrets-controller
      kubeseal_dockerhub_image_name: docker.io/bitnami/sealed-secrets-kubeseal
      kubeseal_ghcr_image_name: ghcr.io/bitnami-labs/sealed-secrets-kubeseal
    steps:
      # Checkout and set env
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
  chart:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          fetch-depth: 0

      - name: Config Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Fetch Version
        run: echo VERSION=$(git describe --tags --match "v[0-9]*" --abbrev=0 | tr -d v) >> "$GITHUB_ENV"

      - name: Update Version
        run: |
          sed -i "s/version: .*/version: ${{ inputs.chart }}/" helm/sealed-secrets/Chart.yaml
          sed -i "s/appVersion: .*/appVersion: $VERSION/" helm/sealed-secrets/Chart.yaml
          sed -i "s/tag: .*/tag: $VERSION/" helm/sealed-secrets/values.yaml
          git checkout -B 'release-chart-${{ inputs.chart }}'
          git add helm/sealed-secrets/Chart.yaml helm/sealed-secrets/values.yaml
          git commit -m 'Release chart ${{ inputs.tag }}'
          git push origin 'release-chart-${{ inputs.chart }}'

      - name: Create PR
        run: gh pr create --fill --base main --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
